---
- hosts: all
  become: yes
  tasks: 
  - name: Install webserver on task01 (apt-get install apache2 -y)
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Install webserver on task02 (yum install httpd )
    yum:
      name: httpd
      state: present
    when: anisble_os_family == "RedHat"
      
