---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Install webserver on task01 (apt-get install apache2 -y)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start webserver on task02 (service apache2 start)
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

      - name: Install webserver on anisble RedHat nodes (yum install httpd -y)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start webserver on anisble RedHat nodes (service httpd start)
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"